<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.018" timestamp="2025-10-17T07:14:05.142254-04:00" hostname="jarvis-core"><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/main.py", line 336, in _main
    config.hook.pytest_collection(session=session)
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 167, in _multicall
    raise exception
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    teardown.throw(exception)
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/logging.py", line 792, in pytest_collection
    return (yield)
            ^^^^^
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    teardown.throw(exception)
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/warnings.py", line 121, in pytest_collection
    return (yield)
            ^^^^^
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    teardown.throw(exception)
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1413, in pytest_collection
    return (yield)
            ^^^^^
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/terminal.py", line 734, in pytest_collection
    self.write("collecting ... ", flush=True, bold=True)
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/terminal.py", line 494, in write
    self._tw.write(content, flush=flush, **markup)
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/_io/terminalwriter.py", line 177, in write
    self.flush()
  File "/mnt/jarvis2/.venv/lib/python3.11/site-packages/_pytest/_io/terminalwriter.py", line 184, in flush
    self._file.flush()
BrokenPipeError: [Errno 32] Broken pipe</error></testcase></testsuite></testsuites>